### ISSUE TITLE
Crash when Downloading JSON data

### ISSUE THREAD

**Issue by CrinanJ** [DominikBuchner/BOLDigger3#11]
Hello,
I'm quite new to this so apologies is this is a dumb question. I have successfully worked in the past with boldigger and boldigger2.
I'm working on Ubuntu and installed boldigger3 and playwright. However, when I run the identify code, the 'Queuing sequences in ID engine' loads perfectly to 100%, but then it crashed the moment 'Downloading JSON data 0%' appears.
Any suggestions? I wonder if it's just a problem with BOLD being overloaded?
I'm attaching a screenshot

![Screenshot 2024-11-05 144244](https://github.com/user-attachments/assets/defd7517-b495-4936-9a0e-b0dfe376534d)

Thanks a lot!

Crinan

**Comment by DominikBuchner** [comment]
Hi Crinan,
have you run `playwright install` after boldigger3 installation? Does restarting the application result in the same issue?

**Comment by LiseKlunder** [comment]
Same here, queuing sequences (only 7k this time) went perfectly within 3 minutes but dowloading JSON data is stuck at 0% for 1h already, not crashed (yet)

**Comment by CrinanJ** [comment]
Thanks for the reply Dominik! Yes I installed playwright and yes the issue continues to occur after restarting.

**Comment by DominikBuchner** [comment]
@LiseKlunder This is expected, sometime the ID engine takes long to answer. Longest I ever saw was 6h, this is fine!

**Comment by DominikBuchner** [comment]
@CrinanJ: Can you open the link in the error message in the browser in your os?

**Comment by CrinanJ** [comment]
Hi Dominik, I can open the link in chrome - see image. So this indicates it's a problem with Ubuntu? 
![Screenshot 2024-11-05 171733](https://github.com/user-attachments/assets/cb61b858-862b-4db8-9c7d-3d9cf439e822)

**Comment by DominikBuchner** [comment]
Not sure yet. Might also be a browser issue, I'll have to test a few things. Can you please update boldigger3 and tell me if the issue persists?

**Comment by LiseKlunder** [comment]
Unfortunately, it did crash after a while for me too

14:39:38: Reading input fasta.
14:39:38: Generating requests.
Queuing sequences in ID engine: 100%|██████████████████████████████████████████████| 7962/7962 [03:20<00:00, 39.71it/s]
14:42:59: Waiting for results to load.
Downloading JSON data:   0%|                                                                  | 0/80 [3:41:03<?, ?it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Scripts\boldigger3.exe\__main__.py", line 7, in <module>
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\__main__.py", line 112, in main
    id_engine.main(
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\id_engine.py", line 468, in main
    download_json(results_urls, hdf_name_results, database, operating_mode)
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\boldigger3\id_engine.py", line 377, in download_json
    page.goto(url)
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\sync_api\_generated.py", line 9002, in goto
    self._sync(
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_page.py", line 553, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lklunder\AppData\Local\Programs\Python\Python312\Lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_NETWORK_IO_SUSPENDED at https://id.boldsystems.org/processing/db_all.bin-tax-derep~mi_0.85~mo_100~maxh_100~order_3-12f0033d75ad4c8a8550c7a535b6f098
Call log:
navigating to "https://id.boldsystems.org/processing/db_all.bin-tax-derep~mi_0.85~mo_100~maxh_100~order_3-12f0033d75ad4c8a8550c7a535b6f098", waiting until "load"

**Comment by DominikBuchner** [comment]
Appears to be a connection issue with the bold website. Will fix tomorrow.

LiseKlunder ***@***.***> schrieb am Di., 5. Nov. 2024, 21:54:

**Comment by DominikBuchner** [comment]
Can you please retry with 1.1.12 and tell me if the issue persists? In the meantime, I'll make up my mind on how to run downloads from previously queued jobs.

**Comment by LiseKlunder** [comment]
I re-ran it yesterday evening, checked this morning and it did finish now. The last upgrade I did was yesterday evening (I run a upgrade everytime before I start)

**Comment by DominikBuchner** [comment]
Perfect. What about you @CrinanJ ?

**Comment by CrinanJ** [comment]
I updated to boldigger3 1.1.12 but unfortunately I still get the same issue as in my initial screenshot...

**Comment by DominikBuchner** [comment]
Okay, can you write me a mail to my working address so I can take a look at what Is going on on your system? Might have to change some of the sourcecode on your system to be able to further troubleshoot.

**Comment by DominikBuchner** [comment]
Apparently, the issue was caused by Ubuntu Subsystem for Windows and we were able to fix it by just running boldigger3 on the windows machine itself with python 3.10.
