### ISSUE TITLE
Another Playwright issue

### ISSUE THREAD

**Issue by hjarnek** [DominikBuchner/BOLDigger3#12]
Hi Dominik,

First of all, a cheerful toast for BOLD v5 and BOLDigger v3! 🍸

I'm having a small issue with Playwright, related to https://github.com/DominikBuchner/BOLDigger3/issues/9. I used to run BOLDigger2 in a conda environment on Ubuntu 24.04. I created a new conda environment for BOLDigger3, but after installation, when I try to run `boldigger3` I get the following message:
```
BEWARE: your OS is not officially supported by Playwright; installing dependencies for ubuntu24.04-x64 as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
```
It then asks for root access and installs the Playwright dependencies, and then finally runs the `boldigger3` command I entered. This happens **every time** I run `boldigger3`, only difference is that after the first time all dependencies are "already the newest version" when it attempts to install them, so it skips installation.

Just wanted to let you know that something's still up with Playwright.

**Comment by DominikBuchner** [comment]
Hi there,
what playwright does is running a headless browser in the background to render the JavaScript on the BOLD website. This is necessary to download the results. That's why it needs an additional install. I'd assume that by running boldigger3 with sudo in front this prompt should go away. Alternatively moving away from the conda environment might help. 

All that said: It's working but annoying, right? I'll see if there's any way to bypass that.

**Comment by DominikBuchner** [comment]
Checked the documentation: Playwright only officially support Ubuntu 18/20/22, that's why the error is thrown. Since it is still working I'll consider this annoying but solved.

**Comment by hjarnek** [comment]
I think the issue here isn't that that Playwright officially only supports a narrow range of distros, as long as the Ubuntu fallback packages are working, but that the fallback packages are attempted to be installed **every time** boldigger3 is run. I don't know if this is on account of Playwright or boldigger, but it's definitely not expected behaviour. And for the record, I run Linux Mint which is Ubuntu based, so I expected it to work, but it seems Playwright only supports official Ubuntu.

**Comment by DominikBuchner** [comment]
I believe this is a playwright issue, so maybe you could open an issue there.

**Comment by V-JJ** [comment]
Hi!

I'm trying to install BOLDDIgger3 on a cluster where I don't have sudo priveleges. So far, I've managed to install BOLDDigger but not playwright which asks for root permissions. Do you have any idea about any alternative way to install playwright?

- This is the error message raised when I tried to run a BOLDDigger3 test. 

Thanks in advance!

```
Password: su: Authentication failure
^MQueuing sequences in ID engine:   0%|          | 0/10 [00:00<?, ?it/s]^MQueuing sequences in ID engine: 100%|██████████| 10/10 [00:00<00:00, 11.17it/s]^MQueuing sequences in ID engine: 100%|██████████| 10/10 [00:00<00:00, 11.16it/s]
Traceback (most recent call last):
  File "/users//anaconda3/envs/BOLDigger3/bin/boldigger3", line 8, in <module>
    sys.exit(main())
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/boldigger3/__main__.py", line 112, in main
    id_engine.main(
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/boldigger3/id_engine.py", line 524, in main
    download_json(
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/boldigger3/id_engine.py", line 365, in download_json
    browser = p.chromium.launch(headless=True)
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 14447, in launch
    self._sync(
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/playwright/_impl/_browser_type.py", line 95, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "/users//anaconda3/envs/BOLDigger3/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 528, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: BrowserType.launch:

Host system is missing dependencies to run browsers. ║
║ Please install them with the following command:      ║
║                                                      ║
║     sudo playwright install-deps
```

Thanks,

**Comment by DominikBuchner** [comment]
Hi there, you will need root permission to install playwright, no way around it. Since BOLDigger3 does not need a loot of computing power, I'd suggest just using your regular computer.

**Comment by V-JJ** [comment]
Understood! Thanks for fast reply!

V

**Comment by marcelpolling** [comment]
Hi Dominic,

I'm also still trying to get boldigger3 to run on my windows environment, but when I run pip install boldigger3 I get the following error message:

![image](https://github.com/user-attachments/assets/e3a3743c-e682-435d-9bdc-334612e1ddaf)

**Comment by DominikBuchner** [comment]
Yes, you need a c compiler which can be installed with visual studio c++
build tools
https://stackoverflow.com/questions/40504552/how-to-install-visual-c-build-tools

marcelpolling ***@***.***> schrieb am Fr., 20. Dez. 2024,
13:39:

**Comment by marcelpolling** [comment]
Hi, thank for the superquick repsonse!

It just keeps throwing errors..:

 .. ERROR:: Could not find a local HDF5 installation headers (hdrdir=None) and/or libdir (libdir=False).                                                        You may need to explicitly state where your local HDF5 headers and                                                                                          library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.

I tried downloading this HDF5 but have no access.. 

![image](https://github.com/user-attachments/assets/1bc145f2-142f-4181-9cfe-639723f3d585)

I am sorry to bother you with all this, I always used boldigger2 without problems in my pipeline on HPC but am having serious issues getting v3 to run

**Comment by DominikBuchner** [comment]
No need to apologize. Could you tell me which operating system this is? WIndows Server?!

**Comment by marcelpolling** [comment]
Hi Dominik, I am trying now using windows powershell on windows 11 running with python version 3.13.1

**Comment by DominikBuchner** [comment]
And this is working or not? I'm confused :D

**Comment by marcelpolling** [comment]
hehe no luck unfortunately.. 

.. ERROR:: Could not find a local HDF5 installation headers (hdrdir=None) and/or libdir (libdir=False).
         You may need to explicitly state where your local HDF5 headers and
         library can be found by setting the ``HDF5_DIR`` environment
         variable or by using the ``--hdf5`` command-line option.**

**Comment by DominikBuchner** [comment]
Okay and this happens during installation of which package? PyTables?

**Comment by marcelpolling** [comment]
no during installation of boldigger3

**Comment by DominikBuchner** [comment]
Canyou make a screenshot of the exact error message?

**Comment by marcelpolling** [comment]
![image](https://github.com/user-attachments/assets/41fe1725-a592-447e-993c-778affbee080)

**Comment by DominikBuchner** [comment]
apparently this is an issue with python 3.13 and pytables. I believe downgrading to 3.12 and then installing via a pre-build wheel from here (https://pypi.org/project/tables/#files) should fix this.

**Comment by marcelpolling** [comment]
Hi Dominik, yes it worked, thank you so much!
