### ISSUE TITLE
Mode 3 hangs and annoying prompt to install dependencies again?

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger3#2]
Hi @DominikBuchner,

Let me first express my heartfelt thanks for all your hard work in developing a new version of BOLDigger in such a short period- this is simply amazing; Hats off to you!

Mode 1 and Mode 2 appears to work for me with these test COI ASV sequences of mine 
[fish_ASVs.fasta.txt](https://github.com/user-attachments/files/17569286/fish_ASVs.fasta.txt)
[algae_ASVs.fasta.txt](https://github.com/user-attachments/files/17569287/algae_ASVs.fasta.txt)

However, Mode 3 simply hangs as below. Also, any way to get rid of that annoying prompt to sudo install dependencies every time I start a new BOLDigger3 session? If I CTRL+C the sudo password prompt, the analysis begins anyways (boldigger3 was pip installed on my python 3.11 conda environment; I had run `playwright install` too). Thank you very much in advance for your help.

```
boldigger3 identify fish_ASVs.fa --db 3 --mode 3
Installing dependencies...
Switching to root user to install dependencies...
[sudo] password for user: 
12:20:51: Reading input fasta.
12:20:51: Generating requests.
Queuing sequences in ID engine: 100%|██████████████████████████████████| 4/4 [00:03<00:00,  1.17it/s]
12:20:55: Waiting for results to load.
Downloading JSON data:   0%|                                                   | 0/1 [00:00<?, ?it/s]

```

**Comment by DominikBuchner** [comment]
Hi Anto,
1. Regarding the "handing". It does not hang, but the queue of BOLD seems to be full. It can stay like that for several hours and then will begin to download. It was the same for me where it took 5 hours for the download to start. My guess is that all jobs submitted to BOLD are put in a queue and this will be worked on one after another. Simply waiting should solve the issue :)
2. I don't know where this prompt comes from and this does NOT originate from BOLDigger's code. So I guess it could be a conda or environment issue but I'm no expert on this. playwright install is documented in the readme I believe, but I will fix the formatting to make it more clear.

All that said: Even with the waiting time, BOLDigger3 will be orders of magnitude faster than the old version. If this process should take more than one day please let me know, the longest I ever saw was 5 hours.

best
Dominik

**Comment by Anto007** [comment]
Thank you @DominikBuchner for your super-quick response-much appreciated! I will try to inspect that annoying prompt further but its something that I can live with ;-) I've got only 4 COI sequences in that test "fish_ASVs.fa" file of mine and if I understood you correctly, it could take up to 5 hours or more for the analysis to finish in mode 3 for these sequences? What if I have 5K or 50K sequences? This mode 3 isn't going to be feasible then? Thanks again.

**Comment by DominikBuchner** [comment]
It depends on how many jobs are queued before you. I cannot tell, this is on the server side of BOLD. Sometime it is immediately, sometimes it takes some time. (as on the website)

**Comment by Anto007** [comment]
ok, let's say BOLD immediately starts my job? What would be the difference in run finish time between 4 sequences and 4K sequences?

**Comment by DominikBuchner** [comment]
4 should be a few minutes, 4k should maybe be 4h. I have not tested all of this, since I was trying to publish as quick as possible.

**Comment by Anto007** [comment]
Sure, I understand @DominikBuchner and thanks again for all your inputs. I'll continue to test the package over the next few days and weeks
