### ISSUE TITLE
Error when installing boldigger3

### ISSUE THREAD

**Issue by balankaleku** [DominikBuchner/BOLDigger3#4]
Hi Dominik,

First of all, thank you for your great contribution. I have to admit that I am not very good with informatics, and I am trying to install your new version (I already used to be a user of the old one) and I got this errors:

`pip install boldigger3`

![image](https://github.com/user-attachments/assets/d4c06aa7-c3f7-4f83-b72b-11e1403e589e)

Any clue what can be going on? I have Python 3.13 and Microsoft Visual Studio properly installed but I got this warning: 

This may not concern you and be a personal issue... But thank you anyway.

Best regards,

Miren

**Comment by balankaleku** [comment]
I updated it in the previous comment

**Comment by DominikBuchner** [comment]
Can you show me the output of `pip freeze`

**Comment by balankaleku** [comment]
No output is shown...

**Comment by DominikBuchner** [comment]
What's the output of `python -m pip install --upgrade pip`. Which OS is this?

**Comment by balankaleku** [comment]
![image](https://github.com/user-attachments/assets/7df587d9-235f-4de0-9926-12d5a1ca4d9b)

I'm working on windows

**Comment by DominikBuchner** [comment]
`python -m pip install numpy==1.24.0`

**Comment by balankaleku** [comment]
No idea what is going wrong here, I'm sorry I don't want to make you waste your time with this... I'll try to solve it some other way...

![image](https://github.com/user-attachments/assets/a3bfe1b2-8e25-4e92-9e44-ebd64c0d7d80)
![image](https://github.com/user-attachments/assets/7ca5f92c-99b6-4344-84db-f3291ab0c88c)
![image](https://github.com/user-attachments/assets/b7d93ac0-0224-437e-9866-ca7bf133785b)

**Comment by DominikBuchner** [comment]
Hi there, all good.

`python -m pip install distutils` and then it should work.

balankaleku ***@***.***> schrieb am Mi., 30. Okt. 2024, 14:10:
