### ISSUE TITLE
ID shifts to last column when taxonomy info is incomplete?

### ISSUE THREAD

**Issue by Anto007** [DominikBuchner/BOLDigger3#8]
Hi @DominikBuchner 

I'm not sure why the below happens (see the row highlighted in yellow) when the taxonomy info is incomplete? Is this intended behavior? Why not just retain those ids in the first column itself instead of moving them to the last?
![image](https://github.com/user-attachments/assets/b28f7ffe-87e7-43e8-933b-7bc78b0d418b)

**Comment by DominikBuchner** [comment]
Not intended, will fix it tomorrow. Thanks for spotting this :)

**Comment by DominikBuchner** [comment]
Fixed with 1.1.8, you can just rerun boldigger3 on the file and it should skip the data downloads and just produce updated results.

**Comment by Anto007** [comment]
Thank you very much for your speedy fix & response. Yes, this is resolved now!
