### ISSUE TITLE
Playwright issue

### ISSUE THREAD

**Issue by OndroV** [DominikBuchner/BOLDigger3#9]
Hello, 

after `playwright install` or even `python3.12 -m playwright install` I get this message:
/home/ono/.local/lib/python3.12/site-packages/playwright/driver/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/ono/.local/lib/python3.12/site-packages/playwright/driver/node)

The same message appears right after starting `python3.12 -m boldigger3 identify my.fasta --db 3 --mode 3`, which can generate the requests, but then stops with error. Any ideas what to do, please?

![image](https://github.com/user-attachments/assets/b6bccef7-3466-4893-a0f9-5b68e07172e9)

This is on WSL Ubuntu 18.04.5 , where python refers to version 3.8.5, so I call `python3.12 -m` in all the commands related with boldigger. I did perform the four pip3.12 commands concerning pyppeteer for boligger2 users.
Seems that this error message is common in many tools ( [1](https://github.com/oven-sh/bun/issues/255) , [2](https://github.com/docker-library/python/issues/421) , [3](https://stackoverflow.com/questions/72921215/getting-glibc-2-28-not-found) ... ) but I'm not sure what to take from the diverging replies there. Soon I will have to move to a newer system anyway, but perhaps there are some easy fixes to broaden boldigger's compatibility?

Thanks!
Ondrej

**Comment by DominikBuchner** [comment]
It seems to be an Ubuntu-specific issue. I will have to do some digging here. Any chance to switch OS and see if the problem persists?

**Comment by OndroV** [comment]
Sure, I totally forgot that windows' command prompt could be useful (after so many disappointments with it :D )
Got an error during installation, but boldigger3 was installed and runs OK so far (downloading json data now)
![image](https://github.com/user-attachments/assets/2f2f1222-3abc-4280-9cea-f9e92b34cd1d)
Thank you very much!

**Comment by TillMacher** [comment]
I have implemented BOLDigger3 in the [apscale conda environment](https://github.com/TillMacher/apscale_installer). This way the installation worked smoothly for me on W11.

**Comment by DominikBuchner** [comment]
Believe this can be closed.

**Comment by marcelpolling** [comment]
Hi there, sorry to reopen this issue, but when I install the apscale environment following TillMachers comment, I can run all the programs in there (apscale, vsearch, blastn) but when I try boldigger3 I only get the availability of boldigger3.exe..? I am not sure how to use that?

**Comment by DominikBuchner** [comment]
Hi there,
I guess the apropriate space to open this issue is at Till's repo

**Comment by TillMacher** [comment]
Yes, please open an issue at my repo and post the exact error that you see in your terminal.

**Comment by OndroV** [comment]
Well, the same error as @marcelpolling [described](https://github.com/TillMacher/apscale_installer/issues/1) is now preventing me from using even the windows terminal or apscale environment for boldigger3 :D ... I have python3.10, so this is not the same [as in the other playwright thread](https://github.com/DominikBuchner/BOLDigger3/issues/12#issuecomment-2559055215).

**Comment by DominikBuchner** [comment]
Can you install pytables from the pre build wheel?

Ondrej Vargovčík ***@***.***> schrieb am Sa., 28. Dez. 2024,
17:57:

**Comment by OndroV** [comment]
Hi, thanks for quick reply. I downloaded the appropriate [whl](https://pypi.org/project/tables/#tables-3.10.1-cp310-cp310-win_amd64.whl) and ran 'pip install tables-3.10.1-cp310-cp310-win_amd64.whl'. All requirements were already satisfied, so I tried even with '--force-reinstall', which produced this:

![image](https://github.com/user-attachments/assets/0ada772c-ff0f-4833-91d4-0e78ce120c58)

Any ideas, please?

**Comment by DominikBuchner** [comment]
Downgrade numpy to 1.4.2, the recent numpy 2 upgrade is not supported by a
lot of dependencies yet

Ondrej Vargovčík ***@***.***> schrieb am So., 29. Dez. 2024,
06:46:

**Comment by OndroV** [comment]
Didn't work :D 
Just for completion, this is the error from boldigger3:

![image](https://github.com/user-attachments/assets/09cebc88-995f-4226-a428-3c5825cf5484)

And this is the outcome of downgrading numpy:

![image](https://github.com/user-attachments/assets/ca3f54af-a80f-472b-881a-884e0dff5ce4)

**Comment by DominikBuchner** [comment]
Okay, sorry was only on the phone due to christmas break. Numpy to version 1.26.4, get-pypi-latest-version to version 0.1.0 and everything should be running again.

**Comment by OndroV** [comment]
That's it, wonderful as always :D Thank you very much and sorry for bothering you even during holidays. Merry Christmas and happy new year :)
